# Generated by Django 4.2.2 on 2023-07-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tagline', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('document', models.FileField(upload_to='doc/')),
            ],
        ),
    ]
