# Generated by Django 4.2.2 on 2023-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_document_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF',
            new_name='PDF_var',
        ),
    ]
